### ISSUE TITLE
A user can rank tasks according to deadline

### ISSUE THREAD

**Issue by dawson123** [cs2103jan2016-w15-3j/main#1]
so that he can settle the more important tasks first.

**Comment by jlin95** [comment]
should the ranking be done automatically or only when the user wants to?

**Comment by dev-seahouse** [comment]
can have a optional "smart ranking" . to implement: each property carry numeric weight. for eg. duetoday:50, piority high: 40: piority middle :30 , piority low: 20.
then, a task that is due today with high piority have 50+40 = 90 , automatically appear on top.
a task that is due today with low piorty = 20 + 50 = 70 --> below
