### ISSUE TITLE
A user should have visual feedback in the app 

### ISSUE THREAD

**Issue by jlin95** [cs2103jan2016-w15-3j/main#16]

**Comment by dev-seahouse** [comment]
When user perform a delete action, there should be unobstructive visual feedback confirming taskTitle and option to undo
When user try to add an event which has a duration already preoccupied by other tasks/event, there should be a unobstrutive warning that allow user to undo within brief period, and disappears seamlessly.

Definition of unobstrutive: Should not be annoying. Should not come with huge warning message. Should be gentle. Should not stop user from continue typing in tasks(aka does not change window focus). Should not reduce user screen realestate as labtops have small screen area and user want to open mail client. More considerations..
