### ISSUE TITLE
Figure out the right parameter required by update() and delete() to identify different Task

### ISSUE THREAD

**Issue by dev-seahouse** [cs2103jan2016-w15-3j/main#39]
Candidates:
1. Each Task object contains a unique ID, then caller calls logic.update(taskID):
Concern: what if a task is deleted ?  
2. Find by index. caller need to know index of Task object stored inside 
Concern:what is tasksList is sorted and index are changed?
3. Find by object. caller pass in an entire Task object. caller.update(task)
Concern: Would it be too complex to implement as the comparisons have to be performed in Logic class to identify which older Task object need to be replaced by the updated Task object.
4.Find by task name
Concern: what if there's a duplicate task name? What if there are two tasks with different dates? What ahout recurring tasks?

**Comment by jlin95** [comment]
If a task is deleted, the arraylist of taskIDs would be automatically updated as well - so with any deletion, a rearrangement is in place internally. I go with 1.

**Comment by dev-seahouse** [comment]
there's another concern with 1: how to generate UID?
We have a few options:
1. integer increment

``` java
public Task{
    public static int IdGenerator = 0;
    private int taskId;
    public Task(){
        this.taskId = idGenerator ++; 
   }
}
```

The problem with this approach is, the idGenerator lives within memory, not persistent, if my guess is not wrong once program restarts, counter reset to 0. That means we might need some sort of file to store current state of IdGenerator in harddisk.
1. UUID

``` java
public class UUIDGenerator {
    public static String nextUUID() {
        return UUID.randomUUID().toString();
    }
}
Output:4e4deff9-b027-4359-8ad5-320e429b5739
```

UUID guarantees that the Ids generated for each Task object is always unique, however.The obvious draw back is, look at how long the id is.

3.

``` java
public class CurrentTimeId {
    private static AtomicReference<Long> currentTime = 
               new AtomicReference<>(System.currentTimeMillis());

    public static Long nextId() {
        return currentTime.accumulateAndGet(System.currentTimeMillis(), 
                   (prev, next) -> next > prev ? next : prev + 1)
    }
}
```

Gaurantees uniqueness, not too long too. stateless.  probably the best solution for now , i guess. out of brain juice
